const ADD_DATA_TO_FORM = 'ADD_DATA_TO_FORM';
const SUBMIT_DATA = 'SUBMIT_DATA';
const ADD_LANGUAGES_TO_STATE = 'ADD_LANGUAGES_TO_STATE';
const ADD_SKILLS_TO_STATE = 'ADD_SKILLS_TO_STATE';
const ADD_HOBBIES_TO_STATE = 'ADD_HOBBIES_TO_STATE';
const HANDLE_VALIDATION = 'HANDLE_VALIDATION';
const HANDLE_REMOVE_VALIDATION_FIELD = 'HANDLE_REMOVE_VALIDATION_FIELD';

export {
    ADD_DATA_TO_FORM,
    SUBMIT_DATA,
    ADD_LANGUAGES_TO_STATE,
    ADD_SKILLS_TO_STATE,
    ADD_HOBBIES_TO_STATE,
    HANDLE_VALIDATION,
    HANDLE_REMOVE_VALIDATION_FIELD
};